### ISSUE TITLE
My browser does not show the font awesome icons

### ISSUE THREAD

**Issue by Skattspa** [smarrerof/angular-bootstrap-template#1]
Hola!
He seguido los pasos de tu ejemplo y revisado tu repositorio.
Tanto chrome como firefox no muestran los iconos de font awesome.
He revisado que estaba utilizando alguno gratuito pero no consigo mostrar ningún icono de la librería.
Solo consigo solucionarlo utilizando un CDN de font awesome en mi index.html.

Me gustaría leerlo de la ruta font-awesome de npm. ¿Me podrías ayudar?

Este es mi angular.json
`{
  "$schema": "./node_modules/@angular/cli/lib/config/schema.json",
  "version": 1,
  "newProjectRoot": "projects",
  "projects": {
    "angular-bootstrap-template": {
      "root": "",
      "sourceRoot": "src",
      "projectType": "application",
      "prefix": "app",
      "schematics": {},
      "architect": {
        "build": {
          "builder": "@angular-devkit/build-angular:browser",
          "options": {
            "outputPath": "dist/angular-bootstrap-template",
            "index": "src/index.html",
            "main": "src/main.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.app.json",
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ],
            "styles": [
              "node_modules/bootstrap/dist/css/bootstrap.css",
              "node_modules/font-awesome/css/font-awesome.css",
              "src/styles.css"
            ],
            "scripts": []
          },
          "configurations": {
            "production": {
              "fileReplacements": [
                {
                  "replace": "src/environments/environment.ts",
                  "with": "src/environments/environment.prod.ts"
                }
              ],
              "optimization": true,
              "outputHashing": "all",
              "sourceMap": false,
              "extractCss": true,
              "namedChunks": false,
              "aot": true,
              "extractLicenses": true,
              "vendorChunk": false,
              "buildOptimizer": true
            }
          }
        },
        "serve": {
          "builder": "@angular-devkit/build-angular:dev-server",
          "options": {
            "browserTarget": "angular-bootstrap-template:build"
          },
          "configurations": {
            "production": {
              "browserTarget": "angular-bootstrap-template:build:production"
            }
          }
        },
        "extract-i18n": {
          "builder": "@angular-devkit/build-angular:extract-i18n",
          "options": {
            "browserTarget": "angular-bootstrap-template:build"
          }
        },
        "test": {
          "builder": "@angular-devkit/build-angular:karma",
          "options": {
            "main": "src/test.ts",
            "polyfills": "src/polyfills.ts",
            "tsConfig": "src/tsconfig.spec.json",
            "karmaConfig": "src/karma.conf.js",
            "styles": [
              "src/styles.css",
              "node_modules/bootstrap/dist/css/bootstrap.css",
              "node_modules/font-awesome/css/font-awesome.css"
            ],
            "scripts": [],
            "assets": [
              "src/favicon.ico",
              "src/assets"
            ]
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": [
              "src/tsconfig.app.json",
              "src/tsconfig.spec.json"
            ],
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    },
    "angular-bootstrap-template-e2e": {
      "root": "e2e/",
      "projectType": "application",
      "architect": {
        "e2e": {
          "builder": "@angular-devkit/build-angular:protractor",
          "options": {
            "protractorConfig": "e2e/protractor.conf.js",
            "devServerTarget": "angular-bootstrap-template:serve"
          },
          "configurations": {
            "production": {
              "devServerTarget": "angular-bootstrap-template:serve:production"
            }
          }
        },
        "lint": {
          "builder": "@angular-devkit/build-angular:tslint",
          "options": {
            "tsConfig": "e2e/tsconfig.e2e.json",
            "exclude": [
              "**/node_modules/**"
            ]
          }
        }
      }
    }
  },
  "defaultProject": "angular-bootstrap-template"
}`

**Comment by smarrerof** [comment]
Hola, ¿qué tal?,

¿que versión de font-awesome tienes en el fichero package.json? A mi con lo que hay en el repositorio se me muestran los iconos de font-awesome tanto en Chrome como en Firefox. Si tienes tu código en un repositorio público le puedo echar un vistazo si quieres.

Saludos.

**Comment by Skattspa** [comment]
Tengo "font-awesome": "^4.7.0"
Puedes echarle un vistazo al proyecto aqui: 
https://github.com/Skattspa/angularBootstrap

Saludos!

**Comment by smarrerof** [comment]
Hola de nuevo,

he descargado tu proyecto y el icono de font-awesome en el texto "Made with..." que está en el app.component.html se ve perfectamente.

¿Cómo estás lanzando el proyecto?¿has hecho un npm install y luego un npm start?

Saludos.

**Comment by Skattspa** [comment]
El fallo estaba en `usar ng` serve en vez de `npm start`.
Creo que era por la version de mi cliente de angular.
Gracias!
